//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wits.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wits.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptRequest {
            get {
                return ResourceManager.GetString("AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Or Block Player.
        /// </summary>
        public static string AddOrBlockPlayer {
            get {
                return ResourceManager.GetString("AddOrBlockPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All My Friends.
        /// </summary>
        public static string AllMyFriends {
            get {
                return ResourceManager.GetString("AllMyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Blocked Player.
        /// </summary>
        public static string AlreadyBlockedPlayer {
            get {
                return ResourceManager.GetString("AlreadyBlockedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player is already blocked.
        /// </summary>
        public static string AlreadyBlockedPlayerMessage {
            get {
                return ResourceManager.GetString("AlreadyBlockedPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey!, This player is already logged in.
        /// </summary>
        public static string AlreadyLogged {
            get {
                return ResourceManager.GetString("AlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block this player?.
        /// </summary>
        public static string BlockConfirmationMesssage {
            get {
                return ResourceManager.GetString("BlockConfirmationMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You blocked this player before.
        /// </summary>
        public static string BlockedBeforeMessage {
            get {
                return ResourceManager.GetString("BlockedBeforeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Blocked.
        /// </summary>
        public static string BlockedBy {
            get {
                return ResourceManager.GetString("BlockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player blocked you!.
        /// </summary>
        public static string BlockedByMessage {
            get {
                return ResourceManager.GetString("BlockedByMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Player.
        /// </summary>
        public static string BlockedPlayer {
            get {
                return ResourceManager.GetString("BlockedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Player.
        /// </summary>
        public static string BlockPlayer {
            get {
                return ResourceManager.GetString("BlockPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player is blocked now!.
        /// </summary>
        public static string BlockPlayerMessage {
            get {
                return ResourceManager.GetString("BlockPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrations.
        /// </summary>
        public static string Celebrations {
            get {
                return ResourceManager.GetString("Celebrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The password must have an uppercase letter, a lowercase letter, a number, a special character, at least 8 characters and can&apos;t be the same as your current password..
        /// </summary>
        public static string ChangePasswordAdvice {
            get {
                return ResourceManager.GetString("ChangePasswordAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the confirmation email.
        /// </summary>
        public static string ConfirmationEmailError {
            get {
                return ResourceManager.GetString("ConfirmationEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Email sent!.
        /// </summary>
        public static string ConfirmationEmailSent {
            get {
                return ResourceManager.GetString("ConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password:.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password:.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Friend.
        /// </summary>
        public static string DeleteFriend {
            get {
                return ResourceManager.GetString("DeleteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this friend?.
        /// </summary>
        public static string DeleteFriendConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteFriendConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The allowed email domains are: outlook.com, gmail.com, hotmail.com and estudiantes.uv.mx.
        /// </summary>
        public static string EmailAdvice {
            get {
                return ResourceManager.GetString("EmailAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There cannot be empty fields.
        /// </summary>
        public static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your answer:.
        /// </summary>
        public static string EnterAnswer {
            get {
                return ResourceManager.GetString("EnterAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount within your available chips..
        /// </summary>
        public static string EnterAValidAmount {
            get {
                return ResourceManager.GetString("EnterAValidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Game ID:.
        /// </summary>
        public static string EnterGameId {
            get {
                return ResourceManager.GetString("EnterGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Player User:.
        /// </summary>
        public static string EnterPlayerUser {
            get {
                return ResourceManager.GetString("EnterPlayerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Request or Friendship.
        /// </summary>
        public static string ExistingRequest {
            get {
                return ResourceManager.GetString("ExistingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a request already or this player is your friend....
        /// </summary>
        public static string ExistingRequestMessage {
            get {
                return ResourceManager.GetString("ExistingRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expel.
        /// </summary>
        public static string Expel {
            get {
                return ResourceManager.GetString("Expel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure about expelling this player?.
        /// </summary>
        public static string ExpelConfirmation {
            get {
                return ResourceManager.GetString("ExpelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were kicked out of the game.
        /// </summary>
        public static string Expelled {
            get {
                return ResourceManager.GetString("Expelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Deleted.
        /// </summary>
        public static string FriendDeleted {
            get {
                return ResourceManager.GetString("FriendDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player is no longer your friend....
        /// </summary>
        public static string FriendDeletedMessage {
            get {
                return ResourceManager.GetString("FriendDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        public static string FriendRequests {
            get {
                return ResourceManager.GetString("FriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends And Requests.
        /// </summary>
        public static string FriendsAndRequests {
            get {
                return ResourceManager.GetString("FriendsAndRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There´s no game with the entered ID.
        /// </summary>
        public static string GameDoesNotExist {
            get {
                return ResourceManager.GetString("GameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get one here!.
        /// </summary>
        public static string GetOneHere {
            get {
                return ResourceManager.GetString("GetOneHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your highest score:.
        /// </summary>
        public static string HighestScore {
            get {
                return ResourceManager.GetString("HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much will you wager?.
        /// </summary>
        public static string HowMuch {
            get {
                return ResourceManager.GetString("HowMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the invitation email.
        /// </summary>
        public static string InvitationEmailError {
            get {
                return ResourceManager.GetString("InvitationEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Email Sent!.
        /// </summary>
        public static string InvitationEmailSent {
            get {
                return ResourceManager.GetString("InvitationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Friend.
        /// </summary>
        public static string InviteFriend {
            get {
                return ResourceManager.GetString("InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string JoinGame {
            get {
                return ResourceManager.GetString("JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        public static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not you current password....
        /// </summary>
        public static string NotCurrentPassword {
            get {
                return ResourceManager.GetString("NotCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Existing Game.
        /// </summary>
        public static string NotExistingGame {
            get {
                return ResourceManager.GetString("NotExistingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is not available or has reached the maximum number of players..
        /// </summary>
        public static string NotExistingGameMessage {
            get {
                return ResourceManager.GetString("NotExistingGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Existing Player.
        /// </summary>
        public static string NotExistingPlayer {
            get {
                return ResourceManager.GetString("NotExistingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That player does not exist....
        /// </summary>
        public static string NotExistingPlayerMessage {
            get {
                return ResourceManager.GetString("NotExistingPlayerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Friends:.
        /// </summary>
        public static string OnlineFriends {
            get {
                return ResourceManager.GetString("OnlineFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The password must have an uppercase letter, a lowercase letter, a number, a special character and at least 8 characters..
        /// </summary>
        public static string PasswordAdvice {
            get {
                return ResourceManager.GetString("PasswordAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been changed successfully!.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string PasswordsUnmatch {
            get {
                return ResourceManager.GetString("PasswordsUnmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as a guest.
        /// </summary>
        public static string PlayAsGuest {
            get {
                return ResourceManager.GetString("PlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Expelled..
        /// </summary>
        public static string PlayerExpelled {
            get {
                return ResourceManager.GetString("PlayerExpelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player was invited!.
        /// </summary>
        public static string PlayerInvitedMessage {
            get {
                return ResourceManager.GetString("PlayerInvitedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        public static string PlayersInGame {
            get {
                return ResourceManager.GetString("PlayersInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Pics.
        /// </summary>
        public static string ProfilePics {
            get {
                return ResourceManager.GetString("ProfilePics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectRequest {
            get {
                return ResourceManager.GetString("RejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember:.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sent.
        /// </summary>
        public static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Request Sent!.
        /// </summary>
        public static string RequestSentMessage {
            get {
                return ResourceManager.GetString("RequestSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round .
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password cannot be the same as your current password..
        /// </summary>
        public static string SamePassword {
            get {
                return ResourceManager.GetString("SamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Problem.
        /// </summary>
        public static string ServerProblem {
            get {
                return ResourceManager.GetString("ServerProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a server problem, Sorry!.
        /// </summary>
        public static string ServerProblemMessage {
            get {
                return ResourceManager.GetString("ServerProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not available.
        /// </summary>
        public static string ServerUnavailable {
            get {
                return ResourceManager.GetString("ServerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s You.
        /// </summary>
        public static string ThatIsYou {
            get {
                return ResourceManager.GetString("ThatIsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, That&apos;s You!.
        /// </summary>
        public static string ThatIsYouMessage {
            get {
                return ResourceManager.GetString("ThatIsYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wits And Wagers.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Here.
        /// </summary>
        public static string TypeHere {
            get {
                return ResourceManager.GetString("TypeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was succesfully created, welcome!.
        /// </summary>
        public static string UserCreatedMessage {
            get {
                return ResourceManager.GetString("UserCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That username is already used or the DB manager is not available, try again.
        /// </summary>
        public static string UsernameUsedMessage {
            get {
                return ResourceManager.GetString("UsernameUsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too weak.
        /// </summary>
        public static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user or password, try again!.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re right!.
        /// </summary>
        public static string YouRight {
            get {
                return ResourceManager.GetString("YouRight", resourceCulture);
            }
        }
    }
}
