//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wits.WitsServiceConnetedUsers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/WitsClasses.Contracts")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CelebrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HighestScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfilePictureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CelebrationId {
            get {
                return this.CelebrationIdField;
            }
            set {
                if ((this.CelebrationIdField.Equals(value) != true)) {
                    this.CelebrationIdField = value;
                    this.RaisePropertyChanged("CelebrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HighestScore {
            get {
                return this.HighestScoreField;
            }
            set {
                if ((this.HighestScoreField.Equals(value) != true)) {
                    this.HighestScoreField = value;
                    this.RaisePropertyChanged("HighestScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfilePictureId {
            get {
                return this.ProfilePictureIdField;
            }
            set {
                if ((this.ProfilePictureIdField.Equals(value) != true)) {
                    this.ProfilePictureIdField = value;
                    this.RaisePropertyChanged("ProfilePictureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WitsServiceConnetedUsers.IPlayerManager")]
    public interface IPlayerManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/AddPlayer", ReplyAction="http://tempuri.org/IPlayerManager/AddPlayerResponse")]
        int AddPlayer(Wits.WitsServiceConnetedUsers.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/AddPlayer", ReplyAction="http://tempuri.org/IPlayerManager/AddPlayerResponse")]
        System.Threading.Tasks.Task<int> AddPlayerAsync(Wits.WitsServiceConnetedUsers.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUser", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserResponse")]
        Wits.WitsServiceConnetedUsers.Player GetPlayerByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUser", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserResponse")]
        System.Threading.Tasks.Task<Wits.WitsServiceConnetedUsers.Player> GetPlayerByUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPassword", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPasswordResponse")]
        Wits.WitsServiceConnetedUsers.Player GetPlayerByUserAndPassword(string username, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPassword", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPasswordResponse")]
        System.Threading.Tasks.Task<Wits.WitsServiceConnetedUsers.Player> GetPlayerByUserAndPasswordAsync(string username, string userPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerChannel : Wits.WitsServiceConnetedUsers.IPlayerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerManagerClient : System.ServiceModel.ClientBase<Wits.WitsServiceConnetedUsers.IPlayerManager>, Wits.WitsServiceConnetedUsers.IPlayerManager {
        
        public PlayerManagerClient() {
        }
        
        public PlayerManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddPlayer(Wits.WitsServiceConnetedUsers.Player player) {
            return base.Channel.AddPlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> AddPlayerAsync(Wits.WitsServiceConnetedUsers.Player player) {
            return base.Channel.AddPlayerAsync(player);
        }
        
        public Wits.WitsServiceConnetedUsers.Player GetPlayerByUser(string username) {
            return base.Channel.GetPlayerByUser(username);
        }
        
        public System.Threading.Tasks.Task<Wits.WitsServiceConnetedUsers.Player> GetPlayerByUserAsync(string username) {
            return base.Channel.GetPlayerByUserAsync(username);
        }
        
        public Wits.WitsServiceConnetedUsers.Player GetPlayerByUserAndPassword(string username, string userPassword) {
            return base.Channel.GetPlayerByUserAndPassword(username, userPassword);
        }
        
        public System.Threading.Tasks.Task<Wits.WitsServiceConnetedUsers.Player> GetPlayerByUserAndPasswordAsync(string username, string userPassword) {
            return base.Channel.GetPlayerByUserAndPasswordAsync(username, userPassword);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WitsServiceConnetedUsers.IConnectedUsers")]
    public interface IConnectedUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/AddConnectedUser", ReplyAction="http://tempuri.org/IConnectedUsers/AddConnectedUserResponse")]
        void AddConnectedUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/AddConnectedUser", ReplyAction="http://tempuri.org/IConnectedUsers/AddConnectedUserResponse")]
        System.Threading.Tasks.Task AddConnectedUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/GetConnectedUsersResponse")]
        string[] GetConnectedUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/GetConnectedUsersResponse")]
        System.Threading.Tasks.Task<string[]> GetConnectedUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/PrintConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/PrintConnectedUsersResponse")]
        void PrintConnectedUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/PrintConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/PrintConnectedUsersResponse")]
        System.Threading.Tasks.Task PrintConnectedUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConnectedUsersChannel : Wits.WitsServiceConnetedUsers.IConnectedUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConnectedUsersClient : System.ServiceModel.ClientBase<Wits.WitsServiceConnetedUsers.IConnectedUsers>, Wits.WitsServiceConnetedUsers.IConnectedUsers {
        
        public ConnectedUsersClient() {
        }
        
        public ConnectedUsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConnectedUsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectedUsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectedUsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddConnectedUser(string username) {
            base.Channel.AddConnectedUser(username);
        }
        
        public System.Threading.Tasks.Task AddConnectedUserAsync(string username) {
            return base.Channel.AddConnectedUserAsync(username);
        }
        
        public string[] GetConnectedUsers() {
            return base.Channel.GetConnectedUsers();
        }
        
        public System.Threading.Tasks.Task<string[]> GetConnectedUsersAsync() {
            return base.Channel.GetConnectedUsersAsync();
        }
        
        public void PrintConnectedUsers() {
            base.Channel.PrintConnectedUsers();
        }
        
        public System.Threading.Tasks.Task PrintConnectedUsersAsync() {
            return base.Channel.PrintConnectedUsersAsync();
        }
    }
}
