//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wits.WitsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/WitsClasses.Contracts")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CelebrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HighestScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProfilePictureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CelebrationId {
            get {
                return this.CelebrationIdField;
            }
            set {
                if ((this.CelebrationIdField.Equals(value) != true)) {
                    this.CelebrationIdField = value;
                    this.RaisePropertyChanged("CelebrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HighestScore {
            get {
                return this.HighestScoreField;
            }
            set {
                if ((this.HighestScoreField.Equals(value) != true)) {
                    this.HighestScoreField = value;
                    this.RaisePropertyChanged("HighestScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfilePictureId {
            get {
                return this.ProfilePictureIdField;
            }
            set {
                if ((this.ProfilePictureIdField.Equals(value) != true)) {
                    this.ProfilePictureIdField = value;
                    this.RaisePropertyChanged("ProfilePictureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/WitsClasses.Contracts")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string answerEN1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string answerES1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string questionEN1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string questionES1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswerEN {
            get {
                return this.AnswerENField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerENField, value) != true)) {
                    this.AnswerENField = value;
                    this.RaisePropertyChanged("AnswerEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswerES {
            get {
                return this.AnswerESField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerESField, value) != true)) {
                    this.AnswerESField = value;
                    this.RaisePropertyChanged("AnswerES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionEN {
            get {
                return this.QuestionENField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionENField, value) != true)) {
                    this.QuestionENField = value;
                    this.RaisePropertyChanged("QuestionEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionES {
            get {
                return this.QuestionESField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionESField, value) != true)) {
                    this.QuestionESField = value;
                    this.RaisePropertyChanged("QuestionES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="answerEN")]
        public string answerEN1 {
            get {
                return this.answerEN1Field;
            }
            set {
                if ((object.ReferenceEquals(this.answerEN1Field, value) != true)) {
                    this.answerEN1Field = value;
                    this.RaisePropertyChanged("answerEN1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="answerES")]
        public string answerES1 {
            get {
                return this.answerES1Field;
            }
            set {
                if ((object.ReferenceEquals(this.answerES1Field, value) != true)) {
                    this.answerES1Field = value;
                    this.RaisePropertyChanged("answerES1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="questionEN")]
        public string questionEN1 {
            get {
                return this.questionEN1Field;
            }
            set {
                if ((object.ReferenceEquals(this.questionEN1Field, value) != true)) {
                    this.questionEN1Field = value;
                    this.RaisePropertyChanged("questionEN1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="questionES")]
        public string questionES1 {
            get {
                return this.questionES1Field;
            }
            set {
                if ((object.ReferenceEquals(this.questionES1Field, value) != true)) {
                    this.questionES1Field = value;
                    this.RaisePropertyChanged("questionES1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WitsService.IPlayerManager")]
    public interface IPlayerManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/AddPlayer", ReplyAction="http://tempuri.org/IPlayerManager/AddPlayerResponse")]
        int AddPlayer(Wits.WitsService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/AddPlayer", ReplyAction="http://tempuri.org/IPlayerManager/AddPlayerResponse")]
        System.Threading.Tasks.Task<int> AddPlayerAsync(Wits.WitsService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUser", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserResponse")]
        Wits.WitsService.Player GetPlayerByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUser", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserResponse")]
        System.Threading.Tasks.Task<Wits.WitsService.Player> GetPlayerByUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPassword", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPasswordResponse")]
        Wits.WitsService.Player GetPlayerByUserAndPassword(string username, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPassword", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayerByUserAndPasswordResponse")]
        System.Threading.Tasks.Task<Wits.WitsService.Player> GetPlayerByUserAndPasswordAsync(string username, string userPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetQuestionByID", ReplyAction="http://tempuri.org/IPlayerManager/GetQuestionByIDResponse")]
        Wits.WitsService.Question GetQuestionByID(int questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetQuestionByID", ReplyAction="http://tempuri.org/IPlayerManager/GetQuestionByIDResponse")]
        System.Threading.Tasks.Task<Wits.WitsService.Question> GetQuestionByIDAsync(int questionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerChannel : Wits.WitsService.IPlayerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerManagerClient : System.ServiceModel.ClientBase<Wits.WitsService.IPlayerManager>, Wits.WitsService.IPlayerManager {
        
        public PlayerManagerClient() {
        }
        
        public PlayerManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlayerManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddPlayer(Wits.WitsService.Player player) {
            return base.Channel.AddPlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> AddPlayerAsync(Wits.WitsService.Player player) {
            return base.Channel.AddPlayerAsync(player);
        }
        
        public Wits.WitsService.Player GetPlayerByUser(string username) {
            return base.Channel.GetPlayerByUser(username);
        }
        
        public System.Threading.Tasks.Task<Wits.WitsService.Player> GetPlayerByUserAsync(string username) {
            return base.Channel.GetPlayerByUserAsync(username);
        }
        
        public Wits.WitsService.Player GetPlayerByUserAndPassword(string username, string userPassword) {
            return base.Channel.GetPlayerByUserAndPassword(username, userPassword);
        }
        
        public System.Threading.Tasks.Task<Wits.WitsService.Player> GetPlayerByUserAndPasswordAsync(string username, string userPassword) {
            return base.Channel.GetPlayerByUserAndPasswordAsync(username, userPassword);
        }
        
        public Wits.WitsService.Question GetQuestionByID(int questionId) {
            return base.Channel.GetQuestionByID(questionId);
        }
        
        public System.Threading.Tasks.Task<Wits.WitsService.Question> GetQuestionByIDAsync(int questionId) {
            return base.Channel.GetQuestionByIDAsync(questionId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WitsService.IConnectedUsers")]
    public interface IConnectedUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/AddConnectedUser", ReplyAction="http://tempuri.org/IConnectedUsers/AddConnectedUserResponse")]
        void AddConnectedUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/AddConnectedUser", ReplyAction="http://tempuri.org/IConnectedUsers/AddConnectedUserResponse")]
        System.Threading.Tasks.Task AddConnectedUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/GetConnectedUsersResponse")]
        string[] GetConnectedUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/GetConnectedUsersResponse")]
        System.Threading.Tasks.Task<string[]> GetConnectedUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/PrintConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/PrintConnectedUsersResponse")]
        void PrintConnectedUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/PrintConnectedUsers", ReplyAction="http://tempuri.org/IConnectedUsers/PrintConnectedUsersResponse")]
        System.Threading.Tasks.Task PrintConnectedUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/RemoveConnectedUser", ReplyAction="http://tempuri.org/IConnectedUsers/RemoveConnectedUserResponse")]
        void RemoveConnectedUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/RemoveConnectedUser", ReplyAction="http://tempuri.org/IConnectedUsers/RemoveConnectedUserResponse")]
        System.Threading.Tasks.Task RemoveConnectedUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetCurrentlyLoggedInUser", ReplyAction="http://tempuri.org/IConnectedUsers/GetCurrentlyLoggedInUserResponse")]
        string GetCurrentlyLoggedInUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetCurrentlyLoggedInUser", ReplyAction="http://tempuri.org/IConnectedUsers/GetCurrentlyLoggedInUserResponse")]
        System.Threading.Tasks.Task<string> GetCurrentlyLoggedInUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetConnectedFriends", ReplyAction="http://tempuri.org/IConnectedUsers/GetConnectedFriendsResponse")]
        string[] GetConnectedFriends(string principalPlayer, string[] allConnectedUsers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConnectedUsers/GetConnectedFriends", ReplyAction="http://tempuri.org/IConnectedUsers/GetConnectedFriendsResponse")]
        System.Threading.Tasks.Task<string[]> GetConnectedFriendsAsync(string principalPlayer, string[] allConnectedUsers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConnectedUsersChannel : Wits.WitsService.IConnectedUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConnectedUsersClient : System.ServiceModel.ClientBase<Wits.WitsService.IConnectedUsers>, Wits.WitsService.IConnectedUsers {
        
        public ConnectedUsersClient() {
        }
        
        public ConnectedUsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConnectedUsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectedUsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConnectedUsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddConnectedUser(string username) {
            base.Channel.AddConnectedUser(username);
        }
        
        public System.Threading.Tasks.Task AddConnectedUserAsync(string username) {
            return base.Channel.AddConnectedUserAsync(username);
        }
        
        public string[] GetConnectedUsers() {
            return base.Channel.GetConnectedUsers();
        }
        
        public System.Threading.Tasks.Task<string[]> GetConnectedUsersAsync() {
            return base.Channel.GetConnectedUsersAsync();
        }
        
        public void PrintConnectedUsers() {
            base.Channel.PrintConnectedUsers();
        }
        
        public System.Threading.Tasks.Task PrintConnectedUsersAsync() {
            return base.Channel.PrintConnectedUsersAsync();
        }
        
        public void RemoveConnectedUser(string username) {
            base.Channel.RemoveConnectedUser(username);
        }
        
        public System.Threading.Tasks.Task RemoveConnectedUserAsync(string username) {
            return base.Channel.RemoveConnectedUserAsync(username);
        }
        
        public string GetCurrentlyLoggedInUser() {
            return base.Channel.GetCurrentlyLoggedInUser();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrentlyLoggedInUserAsync() {
            return base.Channel.GetCurrentlyLoggedInUserAsync();
        }
        
        public string[] GetConnectedFriends(string principalPlayer, string[] allConnectedUsers) {
            return base.Channel.GetConnectedFriends(principalPlayer, allConnectedUsers);
        }
        
        public System.Threading.Tasks.Task<string[]> GetConnectedFriendsAsync(string principalPlayer, string[] allConnectedUsers) {
            return base.Channel.GetConnectedFriendsAsync(principalPlayer, allConnectedUsers);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WitsService.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/CreateGame", ReplyAction="http://tempuri.org/IGameService/CreateGameResponse")]
        void CreateGame(int gameId, string gameLeader, int numberOfPlayers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/CreateGame", ReplyAction="http://tempuri.org/IGameService/CreateGameResponse")]
        System.Threading.Tasks.Task CreateGameAsync(int gameId, string gameLeader, int numberOfPlayers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/JoinGame", ReplyAction="http://tempuri.org/IGameService/JoinGameResponse")]
        int JoinGame(int gameId, string playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/JoinGame", ReplyAction="http://tempuri.org/IGameService/JoinGameResponse")]
        System.Threading.Tasks.Task<int> JoinGameAsync(int gameId, string playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetScores", ReplyAction="http://tempuri.org/IGameService/GetScoresResponse")]
        System.Collections.Generic.Dictionary<string, int> GetScores(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetScores", ReplyAction="http://tempuri.org/IGameService/GetScoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetScoresAsync(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ModifyScore", ReplyAction="http://tempuri.org/IGameService/ModifyScoreResponse")]
        void ModifyScore(int gameId, string playerId, int credits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/ModifyScore", ReplyAction="http://tempuri.org/IGameService/ModifyScoreResponse")]
        System.Threading.Tasks.Task ModifyScoreAsync(int gameId, string playerId, int credits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetPlayerScore", ReplyAction="http://tempuri.org/IGameService/GetPlayerScoreResponse")]
        int GetPlayerScore(int gameId, string playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetPlayerScore", ReplyAction="http://tempuri.org/IGameService/GetPlayerScoreResponse")]
        System.Threading.Tasks.Task<int> GetPlayerScoreAsync(int gameId, string playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetGameLeader", ReplyAction="http://tempuri.org/IGameService/GetGameLeaderResponse")]
        string GetGameLeader(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetGameLeader", ReplyAction="http://tempuri.org/IGameService/GetGameLeaderResponse")]
        System.Threading.Tasks.Task<string> GetGameLeaderAsync(int gameId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : Wits.WitsService.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<Wits.WitsService.IGameService>, Wits.WitsService.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateGame(int gameId, string gameLeader, int numberOfPlayers) {
            base.Channel.CreateGame(gameId, gameLeader, numberOfPlayers);
        }
        
        public System.Threading.Tasks.Task CreateGameAsync(int gameId, string gameLeader, int numberOfPlayers) {
            return base.Channel.CreateGameAsync(gameId, gameLeader, numberOfPlayers);
        }
        
        public int JoinGame(int gameId, string playerId) {
            return base.Channel.JoinGame(gameId, playerId);
        }
        
        public System.Threading.Tasks.Task<int> JoinGameAsync(int gameId, string playerId) {
            return base.Channel.JoinGameAsync(gameId, playerId);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetScores(int gameId) {
            return base.Channel.GetScores(gameId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetScoresAsync(int gameId) {
            return base.Channel.GetScoresAsync(gameId);
        }
        
        public void ModifyScore(int gameId, string playerId, int credits) {
            base.Channel.ModifyScore(gameId, playerId, credits);
        }
        
        public System.Threading.Tasks.Task ModifyScoreAsync(int gameId, string playerId, int credits) {
            return base.Channel.ModifyScoreAsync(gameId, playerId, credits);
        }
        
        public int GetPlayerScore(int gameId, string playerId) {
            return base.Channel.GetPlayerScore(gameId, playerId);
        }
        
        public System.Threading.Tasks.Task<int> GetPlayerScoreAsync(int gameId, string playerId) {
            return base.Channel.GetPlayerScoreAsync(gameId, playerId);
        }
        
        public string GetGameLeader(int gameId) {
            return base.Channel.GetGameLeader(gameId);
        }
        
        public System.Threading.Tasks.Task<string> GetGameLeaderAsync(int gameId) {
            return base.Channel.GetGameLeaderAsync(gameId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WitsService.IChatManager", CallbackContract=typeof(Wits.WitsService.IChatManagerCallback))]
    public interface IChatManager {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/SendNewMessage")]
        void SendNewMessage(string message, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/SendNewMessage")]
        System.Threading.Tasks.Task SendNewMessageAsync(string message, int gameId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/RegisterUserContext")]
        void RegisterUserContext(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/RegisterUserContext")]
        System.Threading.Tasks.Task RegisterUserContextAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/UnregisterUserContext")]
        void UnregisterUserContext(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatManager/UnregisterUserContext")]
        System.Threading.Tasks.Task UnregisterUserContextAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatManager/UpdateChat", ReplyAction="http://tempuri.org/IChatManager/UpdateChatResponse")]
        void UpdateChat(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatManagerChannel : Wits.WitsService.IChatManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatManagerClient : System.ServiceModel.DuplexClientBase<Wits.WitsService.IChatManager>, Wits.WitsService.IChatManager {
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendNewMessage(string message, int gameId) {
            base.Channel.SendNewMessage(message, gameId);
        }
        
        public System.Threading.Tasks.Task SendNewMessageAsync(string message, int gameId) {
            return base.Channel.SendNewMessageAsync(message, gameId);
        }
        
        public void RegisterUserContext(string username) {
            base.Channel.RegisterUserContext(username);
        }
        
        public System.Threading.Tasks.Task RegisterUserContextAsync(string username) {
            return base.Channel.RegisterUserContextAsync(username);
        }
        
        public void UnregisterUserContext(string username) {
            base.Channel.UnregisterUserContext(username);
        }
        
        public System.Threading.Tasks.Task UnregisterUserContextAsync(string username) {
            return base.Channel.UnregisterUserContextAsync(username);
        }
    }
}
